JuliaParallel/ClusterManagers.jl

- src/slurm.jl
When launching the slurm workers I redirect the worker information to files instead of `STDOUT`. The reason for this is that, when working with several nodes, the lines got messed up and were difficult to parse. Writing to files might also make it possible to reconnect, but that is another issue.
It is the first time I write code like this so there is probably things that can be improved, but with this, I'm able to launch 512 workers on the cluster.
We probably want to look into options for specifying `-N` and `-c` instead of only `-n` as the user probably would like to have some control over how the workers are distributed across nodes.
> Use files for retrieving the addresses.

- src/ClusterManagers.jl
- src/qsub.jl
Fixed string interpolation errors and new types in Julia 0.4
> String Interpolation and Immutable Errors

- src/scyld.jl
It's better to use `detach(cmd)` than the undocumented `cmd.detach`, which might change in the near future.
> use detach(cmd), not cmd.detach

- src/ClusterManagers.jl
- src/affinity.jl
- src/condor.jl
- src/qsub.jl
- src/scyld.jl
- src/slurm.jl
ref : https://github.com/JuliaLang/julia/pull/16423
> add support for cookie changes

- README.md
- src/qsub.jl
adds a keyword `res_list` to `addprocs_sge`. This addresses an issue with SGE clusters who require an explicit resource list to be passed (like runtime, memory required etc). This could not be passed via `qsub_env` because we paste the flag `-v` in front of it. the resource list uses flag `-l`.
> Add keyword arg res_list to addprocs_sge to request cluster specific resources

- src/qsub.jl
I was having an issue using the PBS Manager  and I tracked down the issue to julia checking for the wrong jobfile. This may of been the cause of https://github.com/JuliaParallel/ClusterManagers.jl/issues/24 since the symptoms were the same.
This fix works for
```
[lstagner@host ClusterManagers]$ qsub --version
Version: 6.0.0.1
Commit: 21cc3d8b18424c77871cd95265148deb97993d14
```
I am not sure if it works with older versions.
> PBS Updates

- README.md
- src/ClusterManagers.jl
- src/elastic.jl
The `ElasticManager` listens on a port on the master. Workers which connect to it are added to the cluster. Details in the updated README.
Please review/comment on the interface and any suggestions at all.
> RFC/WIP : added elastic manager

- README.md
- src/elastic.jl
`:all_to_all` is used as the default topology. A different one can be specified with the `topology` keyword argument.
`ElasticManager(;addr=IPv4("127.0.0.1"), port=9009, cookie=nothing, topology=:all_to_all)`
ref: #40
> allow topology to be specified for elastic manager

- src/condor.jl
The original `close()` tries to close a `Nullable` object, without the `get()`
> Fixed bug trying to close nullable port

- README.md
Apparently the doc URLs have changed at some point, simple fix.
> Unbreak link to ClusterManagers in Julia manual

- src/qsub.jl
Some PBS clusters have different schematics for standard output files when array jobs are used. This fixes #85 .
> Some PBS clusters have different stdoutput files

- .travis.yml
- REQUIRE
- src/ClusterManagers.jl
- src/affinity.jl
- src/condor.jl
- src/elastic.jl
- src/qsub.jl
- src/scyld.jl
- src/slurm.jl
- test/runtests.jl
- updated for Julia 0.7+
- dropped support for older Julia versions
- enabled basic CI on travis
- updated ElasticManager for 0.7 changes
> make Julia 0.7 compatible

- src/ClusterManagers.jl
- src/slurm.jl
Fixes SLURM functionalities by updating some deprecated syntax in slurm.jl, and replacing cluster_cookie() call. Also adresses a filter() deprecation warning
> minor 0.7+ fixes and updates to slurm.jl

- src/elastic.jl
When multiple connections are pending at the same time, the `s` variable gets overwritten before the previous accepted socket can be passed to `process_worker_conn`.
> race condition for multiple in-bound connections

- README.md
- src/ClusterManagers.jl
- src/lsf.jl
closes https://github.com/JuliaParallel/ClusterManagers.jl/issues/72
> add support for LSF

- src/elastic.jl
This way someone can create an `ElasticManager` with
```julia
em = ElasticManager(port=0)
```
Then get the ephemerally chosen port via `convert(Int, em.sockname[2])`.
> provide sockname for ElasticManager so ephemeral port can be read

- src/qsub.jl
Add support for resource list in `addprocs_qrsh` following the same style of `addprocs_sge` and `addprocs_pbs`. Tested with `h_rt` and `h_vmem` resources on an SGE cluster (OGS/GE 2011.11p1).
> Added res_list to addprocs_qrsh

- src/slurm.jl
I added the environmental variable ENV["SLURM_JOB_ID"] in the naming pattern of the job.out files so that jobs that start simultaneously in the same folder to do not attempt to write on the same files causing errors in the cluster.
> Change the naming pattern of .out files to avoid conflicts

- Project.toml
- README.md
- src/ClusterManagers.jl
- src/elastic.jl
- test/runtests.jl
This adds two things discussed in https://github.com/JuliaParallel/ClusterManagers.jl/issues/128
First, it gives `ElasticManager` the `addr=:auto` option on Linux, which looks up the master's IP address via `hostname --ip-address` so that you get the private IP and other workers on the LAN can connect to it. This isn't foolproof depending on the network setup, but its 4 for 4 on the HPC clusters I have access to. 
Second, it adds a line to what is printed when you evaluate an `ElasticManager`, 
```
julia> em = ElasticManager(addr=:auto, port=0)
ElasticManager:
Active workers : []
Number of workers to be added  : 0
Terminated workers : []
Worker connect command : 
/home/user/bin/julia --project=/home/user/myproject/Project.toml -e 'using ClusterManagers; …
```
> Make ElasticManager more convenient

- README.md
- src/lsf.jl
- test/runtests.jl
much more efficient with the scheduler's resources than with interactive jobs.
i've also added a means to add cluster workers to a personal workstation via a new `ssh_cmd` keyword argument.
> refactor LSFManager to use jobs arrays

- src/slurm.jl
Resolves #127 
Resolves additional bug where the port and IP info are not parsed when a warning or error from the node (e.g. "TMPDIR could not be created") occupies the first lines of the output file.
Related but unnecessary changes:  I removed "job_" from the output file name.  I stopped the automatic deletion of previous logs.  At the very least, that should have a flag associated with it.
> Slurm robust to no jobid and to node warnings

- README.md
- src/qsub.jl
- test/runtests.jl
> simplified qsub call, fixed kill, added working dir option + some tests

- README.md
- src/qsub.jl
Make it clear in the README that the keyword argument includes all flags for `qsub`, not just the queue option.
```
addprocs_sge(3)
```
Error is fixed by making default qsub_flags ``` `` ``` instead of `""`
> clarify qsub flags are not limited to queue and need -q

- src/condor.jl
Currently, HTCManager is pretty rigid in terms of the job submission script and worker node script, and doesn't communicate properly as noted in https://github.com/JuliaParallel/ClusterManagers.jl/issues/150 and https://github.com/JuliaParallel/ClusterManagers.jl/issues/107. 
To address the first, I added parameters that let one send extra inputs to the worker node, insert lines/ClassAds in the job submission script, add extra commands before julia is invoked on the worker node, and modify the location/command used in place of `telnet`. So one can do something like
```julia
myparams = Dict(
:dir=>".",
:exename=>"julia",
:extrainputs=>["/path/to/file1.gz"],
:extrajdl=>["RequestCpus = 1"],
:extraenv=>["tar xf file1.gz", "setup_command()"],
)
addprocs(HTCManager(8); myparams...)
```
and …
> Fix up and add flexibility to HTCManager

- README.md
- src/qsub.jl
I've noticed that`kwargs` were missing in the addproc of qsub. 
This is useful for example to run jobs with `exeflags="--project"` like in #144
> Missing kwargs in qsub addproc

- README.md
As ClusterManagers.jl seems to be the [first place people look for additional cluster managers](https://julialang.slack.com/archives/C674VR0HH/p1626551368170300?thread_ts=1626540412.168100&cid=C674VR0HH) it may be good to include references to external cluster managers as part of the table in the README. 
Other managers that possible should be added could be:
- https://github.com/JuliaParallel/Elly.jl
- https://github.com/JuliaCloud/AWSClusterManagers.jl
There may be a better approach to improving discoverability of Julia cluster managers. This just seemed like an easy approach.
> Add reference to K8sClusterManager in README

- src/lsf.jl
This updates the LSFManager to allow stdout and stderr streams of workers to be streamed (optionally) to master. The `bpeek` invocation when passed the `-f` flag behaves similar to `tail -f`. This is the default set for `bpeek_flags`. The resultant stream is then passed on to the Distributed module after parsing the worker connection string and some initial error handling for the case where job startup is delayed or failed. The Distributed module then takes over the subsequent display of worker's stdout messages on master.
If streaming of worker's stdout messages is not desired, then the `-f` flag can be omitted from `bpeek_flags`. Then `bpeek` behaves similar to `cat` and is used only to read the initial connection string.
As a positive side effect of this change, it now also avoids the …
> LSFManager: optionally stream worker stdout to master

- Project.toml
Updated version to v0.4.1.
Going through the merged PR descriptions, updating patch version seems sufficient for tagging a new version.
> Update patch version for tagging

- .github/workflows/UnitTests.yml
- test/runtests.jl
Start on #105, alternative to #125
Uses container from https://github.com/giovtorres/docker-centos7-slurm
> Add Slurm Docker tests

- Project.toml
This PR bumps to v0.4.3.
The current version v0.4.2 predates the latest change by @David96 which would be useful for running on slurm.
> Bump version with slurm retry_delays fix

- src/lsf.jl
Fixes #182 
Not sure is this is the right way to go about it. Rather than trying to handle a flood of empty strings we just close the stream and open a new one when we think that bpeek has terminated (i.e when bpeek outputs "Not yet started" ).
Not sure what will/should happen when stream is passed over to Distributed if user does not pass -f. Does it know what to do with empty strings or should we close the stream if the process has exited?
> Close and reopen stream after bpeek exits

- src/ClusterManagers.jl
- src/condor.jl
Bug fix:
- `listenany` doesn't guarantee the port number, so we should use the `portnum` returned
- finalizer is bugged, `isnull` doesn't exist
Improvement:
- instead of doing `--worker = <cookie>`, we manually call `start_worker(<cookie>)` such that user can use `-e "..."` to pre-execute stuff. In my case, I want to patch `Sockets.getipaddr()` such that it skips internal private IP range.
This is possible because Julia stacks multiple `-e` command line options
This PR doesn't have impact on any other backend and is backward compatible for Condor
> improvement and bug fix for condor

- Project.toml
- README.md
- src/elastic.jl
Ref discussion at #189
This PR updates the `ElasticManager` constructor to enable support for automatic IP address detection on Windows (and potentially other platforms that aren't macOS or Linux). Prior to this change, a custom `get_private_ip()` function is used to detect the platform and execute system `cmd`s to look for the machine's IP address. These changes obsolete that function in favor of a call to `Sockets.getipaddr()`, a utility that was not available until the v1.2 release of Julia.
It's possible for `Sockets.getipaddr()` to throw an error if no network interfaces are detected, so I've implemented a `try-catch` to generate a helpful error message, suggesting the IP address be specified manually. This message is largely derived from the prior `get_private_ip()` error message.
I …
> Update ElasticManager constructor auto IP config

- src/slurm.jl
- test/runtests.jl
As seen in #185, if an output argument (`-o` or `--output`) is added to the `srun` arguments, the process fails. This checks to see if an output name has been specified and if not, uses the previous default name format.
> add support for specifying slurm output file

- src/slurm.jl
Builds on top of #199.
Before (but with fix in #199):
```
connecting to worker 1 out of 12
connecting to worker 2 out of 12
connecting to worker 3 out of 12
connecting to worker 4 out of 12
connecting to worker 5 out of 12
connecting to worker 6 out of 12
connecting to worker 7 out of 12
connecting to worker 8 out of 12
connecting to worker 9 out of 12
connecting to worker 10 out of 12
connecting to worker 11 out of 12
connecting to worker 12 out of 12
```
After:
```
[ Info: Starting SLURM job julia-26323452: `srun -J julia-26323452 -n 12 -D /homedir/some/dir --cpus-per-task=8 --mem-per-cpu=8G --cpu-bind=cores --mem-bind=local -o /homedir/slurm-julia-output/julia-26323452-12983479872-%4t.out /path/to/bin/julia --project=/homedir/.julia/environments/someenv --threads=8 …
```
> Make SLUM worker startup more robust and provide more feedback

- Project.toml
In preparation for a new release.
> Bump version from `0.4.6` to `0.4.7`

- README.md
Currently, the README has a single table with all implementations. This makes it difficult to quickly realize that some implementations live in this package, while other implementations live in external packages.
This PR splits the table up into two separate tables, to draw this distinction more clearly.
> README: Clearly distinguish between implementations in this package vs external packages

- README.md
Alternative to #197.
The difference from #197 is that in this PR, we explicitly say that we have the goal of splitting up this package (#58).
#197 says "looking for a maintainer" - in this PR, we instead explicitly ask only for people to maintain a single manager. I think this is a more realistic goal. I think it's more likely that we can find e.g. three separate people to maintain three separate managers vs. finding a single person willing to maintain all of the managers that currently live in this package.
> README: Mention that the package is not actively maintained or tested, and add a call for maintainers

- Project.toml
In preparation for a new release.
> Bump version from `0.4.8` to `0.4.9`

- src/condor.jl
- src/qsub.jl
- src/scyld.jl
These managers do not currently have a maintainer. So let's add `depwarn`s. If we are able to recruit a maintainer in the future, we can remove the `depwarn` at that time.
1. SGE (via `qsub` or `qrsh`).
2. PBS (via `qsub`).
3. HTCondor (via `condor_submit`).
4. Scyld ClusterWare (via `bpsh`).
> Add `depwarn`s (but do not remove) the managers that are not currently being maintained (SGE, PBS, HTCondor, and Scyld)

- README.md
> README: Move the unmaintained managers (SGE, PBS, HTCondor, and Scyld) to a separate table

- src/slurm.jl
Depends on:
---
We'll first release a non-breaking release of ClusterManagers.jl with the deprecation warning.
Then, we'll follow-up with a breaking release of ClusterManagers.jl that fully removes the Slurm functionality from this package.
The README (of this package) will point users to the SlurmClusterManager.jl package instead.
> Deprecate (but do not remove) the Slurm functionality in this package (and point users to SlurmClusterManager.jl instead)
